name: 'Build Skeletyl'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["bastardkb/skeletyl"]'
      alphas: '["dvorak"]'
      nav: '["vi"]'
      
